-- auto-generated definition
CREATE TABLE ISMS_DATA_CLASS
(
    CLASS_ID bigint PRIMARY KEY NOT NULL,
    CLASS_TYPE varchar(64) NOT NULL,
    PARENT_ID bigint DEFAULT 0 NOT NULL,
    CLASS_NAME varchar(64)
)

-- auto-generated definition
CREATE TABLE ISMS_DATA_CLASS_FILE
(
    CLASS_ID bigint NOT NULL,
    FILE_ID bigint NOT NULL,
    CONSTRAINT ISMS_DATA_CLASS_FILE_CLASS_ID_FILE_ID_PK PRIMARY KEY (CLASS_ID, FILE_ID)
)

INSERT INTO APP.ISMS_DATA_CLASS (CLASS_ID, CLASS_TYPE, PARENT_ID, CLASS_NAME, POSITION) VALUES (1, 'EVIDENCE', 0, 'ROOT', 0);
INSERT INTO APP.ISMS_DATA_CLASS (CLASS_ID, CLASS_TYPE, PARENT_ID, CLASS_NAME, POSITION) VALUES (2, 'DATA', 0, 'ROOT', 0);
INSERT INTO APP.ISMS_DATA_CLASS (CLASS_ID, CLASS_TYPE, PARENT_ID, CLASS_NAME, POSITION) VALUES (3, 'SECURITY', 0, 'ROOT', 0);

insert into ISMS_DATA_CLASS_FILE(CLASS_ID,FILE_ID) SELECT 1,EVIDENCE_ID from ISMS_EVIDENCE;

CREATE TABLE ISMS_DATA
(
  EVIDENCE_ID BIGINT PRIMARY KEY NOT NULL,
  DESCRIPTION LONG VARCHAR,
  PATH VARCHAR(256),
  CONTENT_TYPE VARCHAR(256),
  ARCHIVED INT DEFAULT 0,
  NAME VARCHAR(256)
);

CREATE TABLE ISMS_SECURITY
(
  EVIDENCE_ID BIGINT PRIMARY KEY NOT NULL,
  DESCRIPTION LONG VARCHAR,
  PATH VARCHAR(256),
  CONTENT_TYPE VARCHAR(256),
  ARCHIVED INT DEFAULT 0,
  NAME VARCHAR(256)
);